Mark the latest v1.19.x release as stable
rancher/k3s pull request #2487
Opened 2020-11-07 00:18 UTC by brandond

#### Proposed Changes ####

Mark the latest v1.19.x release as stable - final task from 2020-10-30 release checklist

#### Types of Changes ####

* Channel

#### Verification ####

* Install k3s from latest channel
* Check version with k3s --version

#### Linked Issues ####

Related to #2460

#### Further Comments ####

2020-11-07 03:44 UTC, davidnuzik commented
We can bump 1.18 but I thought we were not quite ready to mark v1.19.x as stable based on some recent conversations around SELinux? I thought we also wanted some more users to test out etcd.

2020-11-07 03:45 UTC, davidnuzik commented on channel.yaml
> +  latest: v1.19.3+k3s2
```suggestion
  latest: v1.18.10+k3s2
```

2020-11-07 03:45 UTC, davidnuzik requested changes
We can bump 1.18 but I thought we were not quite ready to mark v1.19.x as stable based on some recent conversations around SELinux? I thought we also wanted some more users to test out etcd.

2020-11-07 06:14 UTC, brandond commented
Was it 1.19 that we're not comfortable with, or just not ready to call etcd stable yet?  I can do either. @cjellick ?

2020-11-09 18:42 UTC, davidnuzik commented
Per our discussion today in Standup, we're okay with marking `v1.19.3+k3s2` as stable.

2020-11-09 18:43 UTC, davidnuzik commented on channel.yaml
> +  latest: v1.19.3+k3s2
Per 11/9/20 standup convo, we are okay with v1.19.3+k3s2

2020-11-09 18:43 UTC, davidnuzik approved these changes
LGTM

2020-11-09 19:15 UTC, merged